CREATE DATABASE GAMESTOREDB;
USE GAMESTOREDB;


CREATE TABLE STORE_USER (
 	USER_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  	USER_TYPE VARCHAR(100),
  	EMAIL VARCHAR(50),
  	PASSWORD VARCHAR(50),
  	USERNAME VARCHAR(30),
  	FNAME VARCHAR(50),
  	LNAME VARCHAR(50),
  	PROFILE_PIC VARCHAR(500),
  	BIO VARCHAR(500),
  	PROFILE_PAGE TEXT,
  	REGISTRATION_DATE DATETIME,
  	DATE_OF_BIRTH DATE
);

CREATE TABLE GAME (
	GAME_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  	GAME_TITLE VARCHAR(50),
  	GAME_DESC VARCHAR(300),
  	PUB_DATE DATETIME,
  	PRICE MONEY,
	DEV_ID INT,
	FOREIGN KEY(DEV_ID) REFERENCES STORE_USER(USER_ID)
);

CREATE TABLE PAYMENT (
 	PAYMENT_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  	PAYMENT_METHOD VARCHAR(50)
);

CREATE TABLE ORDER_HEADER (
 	ORDER_HEADER_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PAYMENT_ID INT,
	FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID),
	PLAYER_ID INT,
	FOREIGN KEY(PLAYER_ID) REFERENCES STORE_USER(USER_ID),
  	ORDER_DATE DATETIME,
  	TOTAL_PRICE MONEY
);

CREATE TABLE REVIEW (
 	REVIEW_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	GAME_ID INT,
	FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID),
	PLAYER_ID INT,
	FOREIGN KEY (PLAYER_ID) REFERENCES STORE_USER(USER_ID),
	ORDER_HEADER_ID INT,
	FOREIGN KEY (ORDER_HEADER_ID) REFERENCES ORDER_HEADER(ORDER_HEADER_ID)
);

CREATE TABLE ORDER_DETAIL (
 	ORDER_DETAIL_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ORDER_HEADER_ID INT,
	FOREIGN KEY (ORDER_HEADER_ID) REFERENCES ORDER_HEADER(ORDER_HEADER_ID),
	GAME_ID INT,
	FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID),
  	QTY INT,
  	PRICE MONEY,
  	LINE_TOTAL MONEY
);

CREATE TABLE GENRE (
 	GENRE_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
  	GENRE VARCHAR(30)
);

CREATE TABLE GENRE_GAME (
	GENRE_ID INT NOT NULL,
	GAME_ID INT NOT NULL,
  	PRIMARY KEY (GENRE_ID, GAME_ID),
  	FOREIGN KEY (GENRE_ID) REFERENCES GENRE(GENRE_ID),
  	FOREIGN KEY (GAME_ID) REFERENCES GAME(GAME_ID)
);